package modules

// Port groups used to label why a port matters.
const (
	GroupRemote     = "Remote access"
	GroupWeb        = "Web"
	GroupData       = "Database"
	GroupMail       = "Mail"
	GroupDirectory  = "Directory"
	GroupFile       = "File sharing"
	GroupDevOps     = "DevOps"
	GroupMessaging  = "Messaging"
	GroupMonitor    = "Monitoring"
	GroupNetwork    = "Network"
	GroupIndustrial = "Industrial"
	GroupMedia      = "Media"
	GroupProxy      = "Proxy"
	GroupApp        = "Application"
	GroupVPN        = "VPN"
)

// PortService is a well-known TCP port and the software that usually listens there.
// The catalog slice is ordered by scan importance: earlier entries are probed first.
type PortService struct {
	Port    int
	Service string
	Detail  string
	Group   string
	HTTP    bool
	TLS     bool
	Order   int
}

func svc(port int, service, detail, group string, http, tls bool) PortService {
	return PortService{Port: port, Service: service, Detail: detail, Group: group, HTTP: http, TLS: tls}
}

// portCatalog is the scan order. Keep the most widely exposed, highest-impact
// services at the top so they show up while the rest of the list is still running.
var portCatalog = []PortService{
	svc(22, "SSH", "", GroupRemote, false, false),
	svc(80, "HTTP", "Web server", GroupWeb, true, false),
	svc(443, "HTTPS", "Web server", GroupWeb, true, true),
	svc(3389, "RDP", "Remote Desktop", GroupRemote, false, false),
	svc(21, "FTP", "", GroupFile, false, false),
	svc(445, "SMB", "Windows file sharing", GroupFile, false, false),
	svc(139, "NetBIOS", "Windows session", GroupFile, false, false),
	svc(135, "MSRPC", "Windows RPC", GroupFile, false, false),
	svc(3306, "MySQL", "MySQL / MariaDB", GroupData, false, false),
	svc(5432, "PostgreSQL", "", GroupData, false, false),
	svc(1433, "MSSQL", "Microsoft SQL Server", GroupData, false, false),
	svc(6379, "Redis", "", GroupData, false, false),
	svc(27017, "MongoDB", "", GroupData, false, false),
	svc(9200, "Elasticsearch", "", GroupData, true, false),
	svc(8080, "HTTP", "Tomcat, Jenkins, proxy", GroupWeb, true, false),
	svc(8443, "HTTPS", "Admin console, Plesk", GroupWeb, true, true),
	svc(25, "SMTP", "", GroupMail, false, false),
	svc(587, "SMTP", "Mail submission", GroupMail, false, false),
	svc(465, "SMTPS", "", GroupMail, false, true),
	svc(53, "DNS", "", GroupDirectory, false, false),
	svc(5900, "VNC", "", GroupRemote, false, false),
	svc(23, "Telnet", "", GroupRemote, false, false),
	svc(110, "POP3", "", GroupMail, false, false),
	svc(143, "IMAP", "", GroupMail, false, false),
	svc(993, "IMAPS", "", GroupMail, false, true),
	svc(995, "POP3S", "", GroupMail, false, true),
	svc(389, "LDAP", "", GroupDirectory, false, false),
	svc(636, "LDAPS", "", GroupDirectory, false, true),
	svc(88, "Kerberos", "", GroupDirectory, false, false),
	svc(5985, "WinRM", "", GroupRemote, true, false),
	svc(5986, "WinRM", "WinRM over HTTPS", GroupRemote, true, true),
	svc(1521, "Oracle", "Oracle Database", GroupData, false, false),
	svc(11211, "Memcached", "", GroupData, false, false),
	svc(9042, "Cassandra", "CQL", GroupData, false, false),
	svc(5672, "AMQP", "RabbitMQ", GroupMessaging, false, false),
	svc(15672, "HTTP", "RabbitMQ management", GroupWeb, true, false),
	svc(2375, "Docker", "Docker API", GroupDevOps, true, false),
	svc(2376, "Docker", "Docker API over TLS", GroupDevOps, true, true),
	svc(6443, "Kubernetes", "API server", GroupDevOps, true, true),
	svc(10250, "Kubelet", "", GroupDevOps, true, true),
	svc(8500, "Consul", "", GroupDevOps, true, false),
	svc(8200, "Vault", "HashiCorp Vault", GroupDevOps, true, true),
	svc(2379, "etcd", "", GroupDevOps, true, true),
	svc(9092, "Kafka", "", GroupMessaging, false, false),
	svc(2181, "ZooKeeper", "", GroupDevOps, false, false),
	svc(502, "Modbus", "", GroupIndustrial, false, false),
	svc(102, "S7comm", "Siemens S7", GroupIndustrial, false, false),
	svc(44818, "EtherNet/IP", "", GroupIndustrial, false, false),
	svc(4840, "OPC UA", "", GroupIndustrial, false, false),
	svc(2049, "NFS", "", GroupFile, false, false),
	svc(111, "rpcbind", "", GroupFile, false, false),
	svc(873, "rsync", "", GroupFile, false, false),
	svc(1080, "SOCKS", "SOCKS proxy", GroupProxy, false, false),
	svc(3128, "HTTP", "Squid proxy", GroupProxy, true, false),
	svc(631, "IPP", "Printing", GroupNetwork, true, false),
	svc(9418, "Git", "", GroupDevOps, false, false),
	svc(3000, "HTTP", "Grafana, Gitea, Node", GroupWeb, true, false),
	svc(9090, "HTTP", "Prometheus, admin UI", GroupMonitor, true, false),
	svc(5601, "HTTP", "Kibana", GroupWeb, true, false),
	svc(7474, "HTTP", "Neo4j", GroupData, true, false),
	svc(7687, "Bolt", "Neo4j", GroupData, false, false),
	svc(8529, "HTTP", "ArangoDB", GroupData, true, false),
	svc(5984, "HTTP", "CouchDB", GroupData, true, false),
	svc(8086, "HTTP", "InfluxDB", GroupData, true, false),
	svc(8123, "HTTP", "ClickHouse, Home Assistant", GroupData, true, false),
	svc(9000, "ClickHouse", "ClickHouse, SonarQube, MinIO, PHP-FPM", GroupData, false, false),
	svc(9300, "Elasticsearch", "Transport", GroupData, false, false),
	svc(27018, "MongoDB", "Shard / config", GroupData, false, false),
	svc(27019, "MongoDB", "Shard", GroupData, false, false),
	svc(33060, "MySQL", "X Protocol", GroupData, false, false),
	svc(3307, "MySQL", "Alternate", GroupData, false, false),
	svc(5433, "PostgreSQL", "Alternate", GroupData, false, false),
	svc(6432, "PgBouncer", "", GroupData, false, false),
	svc(3050, "Firebird", "", GroupData, false, false),
	svc(2483, "Oracle", "Listener", GroupData, false, false),
	svc(2484, "Oracle", "Listener over TLS", GroupData, false, true),
	svc(50000, "DB2", "IBM DB2, Jenkins agent", GroupData, false, false),
	svc(26257, "CockroachDB", "", GroupData, false, false),
	svc(28015, "RethinkDB", "", GroupData, false, false),
	svc(28017, "HTTP", "RethinkDB admin", GroupData, true, false),
	svc(8091, "HTTP", "Couchbase", GroupData, true, false),
	svc(11210, "Couchbase", "Data", GroupData, false, false),
	svc(8428, "HTTP", "VictoriaMetrics", GroupData, true, false),
	svc(6333, "HTTP", "Qdrant", GroupData, true, false),
	svc(6334, "Qdrant", "gRPC", GroupData, false, false),
	svc(19530, "Milvus", "", GroupData, false, false),
	svc(7700, "HTTP", "Meilisearch", GroupData, true, false),
	svc(8108, "HTTP", "Typesense", GroupData, true, false),
	svc(6380, "Redis", "Alternate", GroupData, false, false),
	svc(26379, "Redis", "Sentinel", GroupData, false, false),
	svc(9160, "Cassandra", "Thrift", GroupData, false, false),
	svc(7199, "JMX", "Cassandra JMX", GroupData, false, false),
	svc(7000, "Cassandra", "Internode", GroupData, false, false),
	svc(9009, "ClickHouse", "Interserver", GroupData, false, false),
	svc(8983, "HTTP", "Apache Solr", GroupWeb, true, false),
	svc(11434, "HTTP", "Ollama", GroupApp, true, false),
	svc(8000, "HTTP", "Dev server, cameras", GroupWeb, true, false),
	svc(8008, "HTTP", "Alternate web", GroupWeb, true, false),
	svc(8081, "HTTP", "Nexus, alternate web", GroupWeb, true, false),
	svc(8088, "HTTP", "Hadoop YARN", GroupWeb, true, false),
	svc(8888, "HTTP", "Jupyter", GroupWeb, true, false),
	svc(8880, "HTTP", "Plesk", GroupWeb, true, false),
	svc(9001, "HTTP", "MinIO console, Supervisor", GroupWeb, true, false),
	svc(9443, "HTTPS", "Admin console", GroupWeb, true, true),
	svc(10443, "HTTPS", "Alternate", GroupWeb, true, true),
	svc(7443, "HTTPS", "Alternate", GroupWeb, true, true),
	svc(4443, "HTTPS", "Alternate", GroupWeb, true, true),
	svc(2082, "HTTP", "cPanel", GroupWeb, true, false),
	svc(2083, "HTTPS", "cPanel", GroupWeb, true, true),
	svc(2086, "HTTP", "WHM", GroupWeb, true, false),
	svc(2087, "HTTPS", "WHM", GroupWeb, true, true),
	svc(2095, "HTTP", "cPanel webmail", GroupWeb, true, false),
	svc(2096, "HTTPS", "cPanel webmail", GroupWeb, true, true),
	svc(10000, "HTTP", "Webmin, HiveServer2", GroupWeb, true, true),
	svc(4848, "HTTP", "GlassFish admin", GroupWeb, true, false),
	svc(7001, "HTTP", "WebLogic", GroupWeb, true, false),
	svc(7002, "HTTPS", "WebLogic", GroupWeb, true, true),
	svc(9080, "HTTP", "WebSphere", GroupWeb, true, false),
	svc(9990, "HTTP", "WildFly admin", GroupWeb, true, false),
	svc(8009, "AJP", "Tomcat AJP", GroupDevOps, false, false),
	svc(1099, "RMI", "Java RMI registry", GroupDevOps, false, false),
	svc(8834, "HTTPS", "Nessus", GroupMonitor, true, true),
	svc(8065, "HTTP", "Mattermost", GroupApp, true, false),
	svc(5000, "HTTP", "Docker registry, dev server", GroupDevOps, true, false),
	svc(10255, "HTTP", "Kubelet read-only", GroupDevOps, true, false),
	svc(2380, "etcd", "Peer", GroupDevOps, false, true),
	svc(8201, "Vault", "Cluster", GroupDevOps, false, true),
	svc(9093, "Kafka", "TLS", GroupMessaging, false, true),
	svc(5671, "AMQP", "AMQP over TLS", GroupMessaging, false, true),
	svc(15671, "HTTPS", "RabbitMQ management", GroupWeb, true, true),
	svc(4369, "EPMD", "Erlang port mapper", GroupDevOps, false, false),
	svc(25672, "AMQP", "RabbitMQ distribution", GroupMessaging, false, false),
	svc(61616, "ActiveMQ", "OpenWire", GroupMessaging, false, false),
	svc(61613, "STOMP", "ActiveMQ", GroupMessaging, false, false),
	svc(8161, "HTTP", "ActiveMQ console", GroupWeb, true, false),
	svc(1883, "MQTT", "", GroupMessaging, false, false),
	svc(8883, "MQTT", "MQTT over TLS", GroupMessaging, false, true),
	svc(4222, "NATS", "", GroupMessaging, false, false),
	svc(6222, "NATS", "Cluster", GroupMessaging, false, false),
	svc(8222, "HTTP", "NATS monitoring", GroupMonitor, true, false),
	svc(50051, "gRPC", "", GroupDevOps, false, false),
	svc(4646, "HTTP", "Nomad", GroupDevOps, true, false),
	svc(4647, "Nomad", "RPC", GroupDevOps, false, false),
	svc(8300, "Consul", "RPC", GroupDevOps, false, false),
	svc(8600, "DNS", "Consul DNS", GroupDirectory, false, false),
	svc(2888, "ZooKeeper", "Peer", GroupDevOps, false, false),
	svc(3888, "ZooKeeper", "Election", GroupDevOps, false, false),
	svc(7077, "Spark", "Master", GroupDevOps, false, false),
	svc(4040, "HTTP", "Spark UI", GroupWeb, true, false),
	svc(18080, "HTTP", "Spark history", GroupWeb, true, false),
	svc(8020, "HDFS", "NameNode", GroupDevOps, false, false),
	svc(9870, "HTTP", "HDFS NameNode UI", GroupWeb, true, false),
	svc(9864, "HTTP", "HDFS DataNode", GroupWeb, true, false),
	svc(8042, "HTTP", "YARN NodeManager", GroupWeb, true, false),
	svc(9091, "HTTP", "Prometheus pushgateway", GroupMonitor, true, false),
	svc(9100, "Exporter", "Node Exporter, JetDirect", GroupMonitor, false, false),
	svc(19999, "HTTP", "Netdata", GroupMonitor, true, false),
	svc(3100, "HTTP", "Grafana Loki", GroupMonitor, true, false),
	svc(10050, "Zabbix", "Agent", GroupMonitor, false, false),
	svc(10051, "Zabbix", "Server", GroupMonitor, false, false),
	svc(5666, "NRPE", "Nagios", GroupMonitor, false, false),
	svc(6556, "Checkmk", "Agent", GroupMonitor, false, false),
	svc(5044, "Logstash", "Beats", GroupMonitor, false, false),
	svc(9600, "HTTP", "Logstash API", GroupMonitor, true, false),
	svc(1514, "Syslog", "Wazuh / syslog", GroupNetwork, false, false),
	svc(1515, "Wazuh", "Agent auth", GroupNetwork, false, false),
	svc(55000, "HTTP", "Wazuh API", GroupMonitor, true, false),
	svc(514, "Syslog", "syslog, rsh", GroupNetwork, false, false),
	svc(601, "Syslog", "", GroupNetwork, false, false),
	svc(6514, "Syslog", "syslog over TLS", GroupNetwork, false, true),
	svc(12201, "GELF", "Graylog", GroupNetwork, false, false),
	svc(24224, "Fluentd", "", GroupNetwork, false, false),
	svc(2222, "SSH", "DirectAdmin, alternate SSH", GroupRemote, false, false),
	svc(2022, "SSH", "Alternate", GroupRemote, false, false),
	svc(5901, "VNC", "Display :1", GroupRemote, false, false),
	svc(5902, "VNC", "Display :2", GroupRemote, false, false),
	svc(5800, "HTTP", "VNC over HTTP", GroupRemote, true, false),
	svc(8291, "Winbox", "MikroTik", GroupRemote, false, false),
	svc(8728, "API", "MikroTik API", GroupRemote, false, false),
	svc(8729, "API", "MikroTik API over TLS", GroupRemote, false, true),
	svc(4899, "Radmin", "", GroupRemote, false, false),
	svc(512, "rexec", "", GroupRemote, false, false),
	svc(513, "rlogin", "", GroupRemote, false, false),
	svc(6000, "X11", "", GroupRemote, false, false),
	svc(6001, "X11", "", GroupRemote, false, false),
	svc(20, "FTP", "Data", GroupFile, false, false),
	svc(990, "FTPS", "", GroupFile, false, true),
	svc(989, "FTPS", "Data", GroupFile, false, true),
	svc(2121, "FTP", "Alternate", GroupFile, false, false),
	svc(548, "AFP", "Apple filing", GroupFile, false, false),
	svc(4045, "lockd", "NFS lock", GroupFile, false, false),
	svc(3268, "LDAP", "AD global catalog", GroupDirectory, false, false),
	svc(3269, "LDAPS", "AD global catalog", GroupDirectory, false, true),
	svc(464, "Kerberos", "kpasswd", GroupDirectory, false, false),
	svc(9389, "HTTPS", "AD web services", GroupDirectory, true, true),
	svc(853, "DNS", "DNS over TLS", GroupDirectory, false, true),
	svc(2525, "SMTP", "Alternate", GroupMail, false, false),
	svc(26, "SMTP", "Alternate", GroupMail, false, false),
	svc(4190, "Sieve", "ManageSieve", GroupMail, false, false),
	svc(1194, "OpenVPN", "", GroupVPN, false, false),
	svc(1723, "PPTP", "", GroupVPN, false, false),
	svc(1701, "L2TP", "", GroupVPN, false, false),
	svc(8118, "HTTP", "Privoxy", GroupProxy, true, false),
	svc(9050, "SOCKS", "Tor", GroupProxy, false, false),
	svc(554, "RTSP", "", GroupMedia, false, false),
	svc(8554, "RTSP", "Alternate", GroupMedia, false, false),
	svc(1935, "RTMP", "", GroupMedia, false, false),
	svc(37777, "Dahua", "DVR / camera", GroupMedia, false, false),
	svc(5060, "SIP", "", GroupMedia, false, false),
	svc(5061, "SIP", "SIP over TLS", GroupMedia, false, true),
	svc(1720, "H.323", "", GroupMedia, false, false),
	svc(2000, "SCCP", "Cisco CallManager", GroupMedia, false, false),
	svc(3478, "TURN", "STUN / TURN", GroupMedia, false, false),
	svc(5349, "TURN", "TURN over TLS", GroupMedia, false, true),
	svc(5222, "XMPP", "Client", GroupMessaging, false, false),
	svc(5269, "XMPP", "Server", GroupMessaging, false, false),
	svc(5280, "HTTP", "XMPP BOSH", GroupWeb, true, false),
	svc(6667, "IRC", "", GroupMessaging, false, false),
	svc(6697, "IRC", "IRC over TLS", GroupMessaging, false, true),
	svc(194, "IRC", "", GroupMessaging, false, false),
	svc(830, "NETCONF", "", GroupNetwork, false, false),
	svc(593, "RPC", "RPC over HTTP", GroupFile, true, false),
	svc(1911, "Fox", "Niagara Fox", GroupIndustrial, false, false),
	svc(32400, "HTTP", "Plex", GroupApp, true, false),
	svc(8096, "HTTP", "Jellyfin, Emby", GroupApp, true, false),
	svc(8989, "HTTP", "Sonarr", GroupApp, true, false),
	svc(7878, "HTTP", "Radarr", GroupApp, true, false),
	svc(9696, "HTTP", "Prowlarr", GroupApp, true, false),
	svc(8686, "HTTP", "Lidarr", GroupApp, true, false),
	svc(25565, "Minecraft", "", GroupApp, false, false),
	svc(7860, "HTTP", "Gradio", GroupApp, true, false),
	svc(8188, "HTTP", "ComfyUI", GroupApp, true, false),
	svc(4200, "HTTP", "Angular dev server", GroupWeb, true, false),
	svc(5173, "HTTP", "Vite", GroupWeb, true, false),
	svc(4000, "HTTP", "Dev server", GroupWeb, true, false),
	svc(8787, "HTTP", "RStudio", GroupWeb, true, false),
	svc(6006, "HTTP", "TensorBoard", GroupWeb, true, false),
	svc(8082, "HTTP", "Alternate web", GroupWeb, true, false),
	svc(8083, "HTTP", "Alternate web", GroupWeb, true, false),
	svc(8084, "HTTP", "Alternate web", GroupWeb, true, false),
	svc(8085, "HTTP", "Alternate web", GroupWeb, true, false),
	svc(8090, "HTTP", "Alternate web", GroupWeb, true, false),
	svc(8181, "HTTP", "Alternate web", GroupWeb, true, false),
	svc(8889, "HTTP", "Alternate web", GroupWeb, true, false),
	svc(5443, "HTTPS", "Alternate", GroupWeb, true, true),
	svc(4433, "HTTPS", "Alternate", GroupWeb, true, true),
	svc(10256, "HTTP", "kube-proxy health", GroupDevOps, true, false),
	svc(4243, "HTTP", "Docker API (legacy)", GroupDevOps, true, false),
	svc(20000, "HTTP", "Usermin", GroupWeb, true, false),
}

// KnownPorts returns a copy of the catalog in scan order.
func KnownPorts() []PortService {
	out := make([]PortService, len(portCatalog))
	copy(out, portCatalog)
	for i := range out {
		out[i].Order = i + 1
	}
	return out
}
